/*
  This class has been generated by the Code Generator
*/

package com.northwind;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;


public class Employees extends EmployeesBase
{
    public Employees()
    {
        this((BusObjectConfig)null);
    }

    public Employees(BusObjectConfig config)
    {
        super(config);
    }

}
